from __future__ import annotations
"""
CBZ (Comic Book ZIP) export service.
Creates standard CBZ format with ComicInfo.xml metadata.
"""
import io
import zipfile
import logging
import xml.etree.ElementTree as ET
from typing import List, Dict, Any, Optional
from datetime import datetime

logger = logging.getLogger(__name__)


class CBZExporter:
    """Export manga pages as CBZ (Comic Book ZIP) format."""

    async def export_to_cbz(
        self,
        pages: List[Dict[str, Any]],
        output_buffer: io.BytesIO,
        metadata: Optional[Dict[str, Any]] = None,
        include_comicinfo: bool = True,
        image_format: str = "png",
    ) -> io.BytesIO:
        """
        Export pages as CBZ file.
        
        Args:
            pages: List of {image_data, page_number, caption} dicts
            output_buffer: BytesIO buffer
            metadata: {title, series, number, summary, writer, penciller, language, genre}
            include_comicinfo: Include ComicInfo.xml metadata
            image_format: Image format for pages (png, jpg, webp)
        
        Returns:
            BytesIO with CBZ data
        """
        metadata = metadata or {}
        
        with zipfile.ZipFile(output_buffer, "w", zipfile.ZIP_DEFLATED) as zf:
            # Add page images
            ext_map = {"png": ".png", "jpg": ".jpg", "jpeg": ".jpg", "webp": ".webp"}
            ext = ext_map.get(image_format, ".png")
            
            for page in sorted(pages, key=lambda p: p.get("page_number", 0)):
                image_data = page.get("image_data")
                if not image_data:
                    continue
                
                page_num = page.get("page_number", 0)
                # Zero-padded 3-digit filename
                filename = f"{page_num:03d}{ext}"
                
                # Convert to target format if needed
                if image_format in ("jpg", "jpeg") and not page.get("is_jpeg"):
                    try:
                        from PIL import Image
                        img = Image.open(io.BytesIO(image_data))
                        buf = io.BytesIO()
                        img.convert("RGB").save(buf, format="JPEG", quality=90)
                        image_data = buf.getvalue()
                    except Exception as e:
                        logger.warning(f"Failed to convert to JPEG: {e}")
                
                zf.writestr(filename, image_data)
            
            # Add ComicInfo.xml
            if include_comicinfo:
                comicinfo_xml = self._generate_comicinfo_xml(metadata, len(pages))
                zf.writestr("ComicInfo.xml", comicinfo_xml)
        
        output_buffer.seek(0)
        return output_buffer

    def _generate_comicinfo_xml(self, metadata: Dict[str, Any], page_count: int) -> str:
        """
        Generate ComicInfo.xml metadata per ComicRack/ComicInfo schema.
        
        https://github.com/anansi-project/comicinfo
        """
        root = ET.Element("ComicInfo")
        root.set("xmlns:xsi", "http://www.w3.org/2001/XMLSchema-instance")
        root.set("xmlns:xsd", "http://www.w3.org/2001/XMLSchema")
        
        # Basic info
        self._add_element(root, "Title", metadata.get("title", "Untitled"))
        self._add_element(root, "Series", metadata.get("series", metadata.get("title", "")))
        self._add_element(root, "Number", str(metadata.get("number", "")))
        self._add_element(root, "Summary", metadata.get("summary", ""))
        self._add_element(root, "Notes", metadata.get("notes", f"Generated by Manga Translator on {datetime.now().strftime('%Y-%m-%d')}"))
        
        # Creators
        self._add_element(root, "Writer", metadata.get("writer", metadata.get("author", "")))
        self._add_element(root, "Penciller", metadata.get("penciller", ""))
        self._add_element(root, "Inker", metadata.get("inker", ""))
        self._add_element(root, "Colorist", metadata.get("colorist", ""))
        self._add_element(root, "Letterer", metadata.get("letterer", ""))
        self._add_element(root, "CoverArtist", metadata.get("cover_artist", ""))
        self._add_element(root, "Editor", metadata.get("editor", ""))
        self._add_element(root, "Translator", metadata.get("translator", "Manga Translator AI"))
        
        # Publishing
        self._add_element(root, "Publisher", metadata.get("publisher", ""))
        self._add_element(root, "Imprint", metadata.get("imprint", ""))
        self._add_element(root, "Genre", metadata.get("genre", "Manga"))
        self._add_element(root, "Web", metadata.get("web", ""))
        self._add_element(root, "PageCount", str(page_count))
        self._add_element(root, "LanguageISO", metadata.get("language", "ja"))
        self._add_element(root, "Format", "Manga")
        
        # Manga specific
        self._add_element(root, "Manga", "Yes")
        self._add_element(root, "Manga", "YesAndRightToLeft")
        self._add_element(root, "AgeRating", metadata.get("age_rating", "Unknown"))
        self._add_element(root, "CommunityRating", str(metadata.get("rating", "")))
        
        # Dates
        self._add_element(root, "Year", str(metadata.get("year", datetime.now().year)))
        self._add_element(root, "Month", str(metadata.get("month", datetime.now().month)))
        self._add_element(root, "Day", str(metadata.get("day", datetime.now().day)))
        
        # Convert to pretty XML string
        xml_str = ET.tostring(root, encoding="unicode", xml_declaration=True)
        
        # Pretty print
        import xml.dom.minidom as md
        dom = md.parseString(xml_str)
        return dom.toprettyxml(indent="  ")

    @staticmethod
    def _add_element(parent, tag, text):
        """Add element only if text is not empty."""
        if text:
            elem = ET.SubElement(parent, tag)
            elem.text = str(text)
